class ChangeIngredientsToStrings < ActiveRecord::Migration[5.2]
  def change
    change_column(:cocktails, :ingredient1, :string)
    change_column(:cocktails, :ingredient2, :string)
    change_column(:cocktails, :ingredient3, :string)
    change_column(:cocktails, :ingredient4, :string)
    change_column(:cocktails, :ingredient5, :string)
    change_column(:cocktails, :ingredient6, :string)
    change_column(:cocktails, :ingredient7, :string)
    change_column(:cocktails, :ingredient8, :string)
    change_column(:cocktails, :ingredient9, :string)
    change_column(:cocktails, :ingredient10, :string)
    change_column(:cocktails, :ingredient11, :string)
    change_column(:cocktails, :ingredient12, :string)
    change_column(:cocktails, :ingredient13, :string)
    change_column(:cocktails, :ingredient14, :string)
    change_column(:cocktails, :ingredient15, :string)
    change_column(:cocktails, :measure1, :string)
    change_column(:cocktails, :measure2, :string)
    change_column(:cocktails, :measure3, :string)
    change_column(:cocktails, :measure4, :string)
    change_column(:cocktails, :measure5, :string)
    change_column(:cocktails, :measure6, :string)
    change_column(:cocktails, :measure7, :string)
    change_column(:cocktails, :measure8, :string)
    change_column(:cocktails, :measure9, :string)
    change_column(:cocktails, :measure10, :string)
    change_column(:cocktails, :measure11, :string)
    change_column(:cocktails, :measure12, :string)
    change_column(:cocktails, :measure13, :string)
    change_column(:cocktails, :measure14, :string)
    change_column(:cocktails, :measure15, :string)    
  end
end
