class ChangeIngredientsToSeperateTables < ActiveRecord::Migration[5.2]
  def change
    add_column(:cocktails, :ingredient1, :text)
    add_column(:cocktails, :ingredient2, :text)
    add_column(:cocktails, :ingredient3, :text)
    add_column(:cocktails, :ingredient4, :text)
    add_column(:cocktails, :ingredient5, :text)
    add_column(:cocktails, :ingredient6, :text)
    add_column(:cocktails, :ingredient7, :text)
    add_column(:cocktails, :ingredient8, :text)
    add_column(:cocktails, :ingredient9, :text)
    add_column(:cocktails, :ingredient10, :text)
    add_column(:cocktails, :ingredient11, :text)
    add_column(:cocktails, :ingredient12, :text)
    add_column(:cocktails, :ingredient13, :text)
    add_column(:cocktails, :ingredient14, :text)
    add_column(:cocktails, :ingredient15, :text)
    add_column(:cocktails, :measure1, :text)
    add_column(:cocktails, :measure2, :text)
    add_column(:cocktails, :measure3, :text)
    add_column(:cocktails, :measure4, :text)
    add_column(:cocktails, :measure5, :text)
    add_column(:cocktails, :measure6, :text)
    add_column(:cocktails, :measure7, :text)
    add_column(:cocktails, :measure8, :text)
    add_column(:cocktails, :measure9, :text)
    add_column(:cocktails, :measure10, :text)
    add_column(:cocktails, :measure11, :text)
    add_column(:cocktails, :measure12, :text)
    add_column(:cocktails, :measure13, :text)
    add_column(:cocktails, :measure14, :text)
    add_column(:cocktails, :measure15, :text)
  end
end
